import { db } from '@/db';
import { inventoryMovements } from '@/db/schema';

async function main() {
    const now = Date.now();
    const thirtyDaysAgo = now - (30 * 24 * 60 * 60 * 1000);
    
    const getRandomTimestamp = (daysAgo: number, range: number = 1) => {
        const startTime = now - (daysAgo * 24 * 60 * 60 * 1000);
        const endTime = startTime + (range * 24 * 60 * 60 * 1000);
        return Math.floor(startTime + Math.random() * (endTime - startTime));
    };

    const sampleMovements = [
        // Recent movements (last 7 days) - 40% of records (20 movements)
        
        // Day 1-2 (today and yesterday) - 8 movements
        {
            productId: 4,
            type: 'sale',
            quantity: 3,
            previousStock: 7,
            newStock: 4,
            reason: 'Order #PK-10001',
            orderId: 1,
            createdBy: 'Maria Lopez',
            createdAt: getRandomTimestamp(0, 0.5),
        },
        {
            productId: 7,
            type: 'reduction',
            quantity: 2,
            previousStock: 6,
            newStock: 4,
            reason: 'Damaged during prep',
            orderId: null,
            createdBy: 'Carlos Ruiz',
            createdAt: getRandomTimestamp(0.5, 0.5),
        },
        {
            productId: 2,
            type: 'sale',
            quantity: 5,
            previousStock: 42,
            newStock: 37,
            reason: 'Sold to customer',
            orderId: null,
            createdBy: 'Admin',
            createdAt: getRandomTimestamp(1, 0.3),
        },
        {
            productId: 8,
            type: 'addition',
            quantity: 30,
            previousStock: 25,
            newStock: 55,
            reason: 'Weekly delivery',
            orderId: null,
            createdBy: 'Manager',
            createdAt: getRandomTimestamp(1.2, 0.3),
        },
        {
            productId: 12,
            type: 'sale',
            quantity: 2,
            previousStock: 5,
            newStock: 3,
            reason: 'Order #PK-10002',
            orderId: 2,
            createdBy: 'Maria Lopez',
            createdAt: getRandomTimestamp(1.5, 0.2),
        },
        {
            productId: 1,
            type: 'sale',
            quantity: 8,
            previousStock: 38,
            newStock: 30,
            reason: 'Walk-in customer',
            orderId: null,
            createdBy: 'Carlos Ruiz',
            createdAt: getRandomTimestamp(1.7, 0.3),
        },
        {
            productId: 5,
            type: 'adjustment',
            quantity: -3,
            previousStock: 33,
            newStock: 30,
            reason: 'Inventory count correction',
            orderId: null,
            createdBy: 'System',
            createdAt: getRandomTimestamp(2, 0.2),
        },
        {
            productId: 9,
            type: 'return',
            quantity: 2,
            previousStock: 18,
            newStock: 20,
            reason: 'Customer return - wrong order',
            orderId: null,
            createdBy: 'Admin',
            createdAt: getRandomTimestamp(2.2, 0.3),
        },

        // Day 3-5 - 7 movements
        {
            productId: 3,
            type: 'addition',
            quantity: 25,
            previousStock: 30,
            newStock: 55,
            reason: 'Restock from supplier',
            orderId: null,
            createdBy: 'Manager',
            createdAt: getRandomTimestamp(3, 0.5),
        },
        {
            productId: 6,
            type: 'sale',
            quantity: 4,
            previousStock: 28,
            newStock: 24,
            reason: 'Phone order',
            orderId: null,
            createdBy: 'Maria Lopez',
            createdAt: getRandomTimestamp(3.5, 0.3),
        },
        {
            productId: 10,
            type: 'reduction',
            quantity: 1,
            previousStock: 22,
            newStock: 21,
            reason: 'Expired ingredients',
            orderId: null,
            createdBy: 'Carlos Ruiz',
            createdAt: getRandomTimestamp(4, 0.2),
        },
        {
            productId: 4,
            type: 'reduction',
            quantity: 1,
            previousStock: 5,
            newStock: 4,
            reason: 'Quality control removal',
            orderId: null,
            createdBy: 'Manager',
            createdAt: getRandomTimestamp(4.3, 0.3),
        },
        {
            productId: 11,
            type: 'sale',
            quantity: 6,
            previousStock: 35,
            newStock: 29,
            reason: 'Order #PK-10003',
            orderId: 3,
            createdBy: 'Admin',
            createdAt: getRandomTimestamp(4.6, 0.2),
        },
        {
            productId: 1,
            type: 'addition',
            quantity: 20,
            previousStock: 30,
            newStock: 50,
            reason: 'Bulk purchase',
            orderId: null,
            createdBy: 'Manager',
            createdAt: getRandomTimestamp(5, 0.3),
        },
        {
            productId: 7,
            type: 'sale',
            quantity: 3,
            previousStock: 7,
            newStock: 4,
            reason: 'Sold to customer',
            orderId: null,
            createdBy: 'Carlos Ruiz',
            createdAt: getRandomTimestamp(5.5, 0.3),
        },

        // Day 6-7 - 5 movements
        {
            productId: 2,
            type: 'sale',
            quantity: 7,
            previousStock: 37,
            newStock: 30,
            reason: 'Walk-in customer',
            orderId: null,
            createdBy: 'Maria Lopez',
            createdAt: getRandomTimestamp(6, 0.3),
        },
        {
            productId: 8,
            type: 'reduction',
            quantity: 3,
            previousStock: 55,
            newStock: 52,
            reason: 'Staff meal',
            orderId: null,
            createdBy: 'Admin',
            createdAt: getRandomTimestamp(6.3, 0.2),
        },
        {
            productId: 12,
            type: 'adjustment',
            quantity: 5,
            previousStock: 3,
            newStock: 8,
            reason: 'Physical count adjustment',
            orderId: null,
            createdBy: 'System',
            createdAt: getRandomTimestamp(6.5, 0.3),
        },
        {
            productId: 5,
            type: 'sale',
            quantity: 4,
            previousStock: 30,
            newStock: 26,
            reason: 'Order #PK-10004',
            orderId: 4,
            createdBy: 'Carlos Ruiz',
            createdAt: getRandomTimestamp(7, 0.2),
        },
        {
            productId: 9,
            type: 'addition',
            quantity: 15,
            previousStock: 20,
            newStock: 35,
            reason: 'Weekly delivery',
            orderId: null,
            createdBy: 'Manager',
            createdAt: getRandomTimestamp(7.3, 0.3),
        },

        // Week 2-3 (8-21 days ago) - 35% of records (17 movements)
        
        // Days 8-11 - 6 movements
        {
            productId: 3,
            type: 'sale',
            quantity: 9,
            previousStock: 55,
            newStock: 46,
            reason: 'Phone order',
            orderId: null,
            createdBy: 'Admin',
            createdAt: getRandomTimestamp(8, 1),
        },
        {
            productId: 6,
            type: 'addition',
            quantity: 35,
            previousStock: 24,
            newStock: 59,
            reason: 'Restock from supplier',
            orderId: null,
            createdBy: 'Manager',
            createdAt: getRandomTimestamp(9, 0.5),
        },
        {
            productId: 10,
            type: 'sale',
            quantity: 5,
            previousStock: 21,
            newStock: 16,
            reason: 'Sold to customer',
            orderId: null,
            createdBy: 'Maria Lopez',
            createdAt: getRandomTimestamp(9.5, 0.5),
        },
        {
            productId: 4,
            type: 'addition',
            quantity: 20,
            previousStock: 4,
            newStock: 24,
            reason: 'Special order arrival',
            orderId: null,
            createdBy: 'Manager',
            createdAt: getRandomTimestamp(10, 0.5),
        },
        {
            productId: 11,
            type: 'reduction',
            quantity: 2,
            previousStock: 29,
            newStock: 27,
            reason: 'Damaged during prep',
            orderId: null,
            createdBy: 'Carlos Ruiz',
            createdAt: getRandomTimestamp(10.5, 0.5),
        },
        {
            productId: 1,
            type: 'sale',
            quantity: 12,
            previousStock: 50,
            newStock: 38,
            reason: 'Order #PK-10005',
            orderId: 5,
            createdBy: 'Admin',
            createdAt: getRandomTimestamp(11, 0.5),
        },

        // Days 12-15 - 6 movements
        {
            productId: 7,
            type: 'addition',
            quantity: 25,
            previousStock: 4,
            newStock: 29,
            reason: 'Bulk purchase',
            orderId: null,
            createdBy: 'Manager',
            createdAt: getRandomTimestamp(12, 1),
        },
        {
            productId: 2,
            type: 'reduction',
            quantity: 4,
            previousStock: 30,
            newStock: 26,
            reason: 'Quality control removal',
            orderId: null,
            createdBy: 'Admin',
            createdAt: getRandomTimestamp(13, 0.5),
        },
        {
            productId: 8,
            type: 'sale',
            quantity: 8,
            previousStock: 52,
            newStock: 44,
            reason: 'Walk-in customer',
            orderId: null,
            createdBy: 'Maria Lopez',
            createdAt: getRandomTimestamp(13.5, 0.5),
        },
        {
            productId: 12,
            type: 'sale',
            quantity: 3,
            previousStock: 8,
            newStock: 5,
            reason: 'Phone order',
            orderId: null,
            createdBy: 'Carlos Ruiz',
            createdAt: getRandomTimestamp(14, 0.5),
        },
        {
            productId: 5,
            type: 'adjustment',
            quantity: 8,
            previousStock: 26,
            newStock: 34,
            reason: 'Stock audit',
            orderId: null,
            createdBy: 'System',
            createdAt: getRandomTimestamp(14.5, 0.5),
        },
        {
            productId: 9,
            type: 'return',
            quantity: 1,
            previousStock: 35,
            newStock: 36,
            reason: 'Cancelled order refund',
            orderId: null,
            createdBy: 'Admin',
            createdAt: getRandomTimestamp(15, 0.5),
        },

        // Days 16-21 - 5 movements
        {
            productId: 3,
            type: 'addition',
            quantity: 30,
            previousStock: 46,
            newStock: 76,
            reason: 'Weekly delivery',
            orderId: null,
            createdBy: 'Manager',
            createdAt: getRandomTimestamp(16, 1),
        },
        {
            productId: 6,
            type: 'sale',
            quantity: 15,
            previousStock: 59,
            newStock: 44,
            reason: 'Sold to customer',
            orderId: null,
            createdBy: 'Maria Lopez',
            createdAt: getRandomTimestamp(17, 1),
        },
        {
            productId: 10,
            type: 'reduction',
            quantity: 3,
            previousStock: 16,
            newStock: 13,
            reason: 'Expired ingredients',
            orderId: null,
            createdBy: 'Carlos Ruiz',
            createdAt: getRandomTimestamp(18, 1),
        },
        {
            productId: 4,
            type: 'sale',
            quantity: 10,
            previousStock: 24,
            newStock: 14,
            reason: 'Walk-in customer',
            orderId: null,
            createdBy: 'Admin',
            createdAt: getRandomTimestamp(19, 1),
        },
        {
            productId: 11,
            type: 'adjustment',
            quantity: -5,
            previousStock: 27,
            newStock: 22,
            reason: 'System sync',
            orderId: null,
            createdBy: 'System',
            createdAt: getRandomTimestamp(20, 1),
        },

        // Weeks 3-4 (22-30 days ago) - 25% of records (13 movements)
        
        // Days 22-25 - 5 movements
        {
            productId: 1,
            type: 'addition',
            quantity: 40,
            previousStock: 38,
            newStock: 78,
            reason: 'Restock from supplier',
            orderId: null,
            createdBy: 'Manager',
            createdAt: getRandomTimestamp(22, 1),
        },
        {
            productId: 7,
            type: 'sale',
            quantity: 14,
            previousStock: 29,
            newStock: 15,
            reason: 'Phone order',
            orderId: null,
            createdBy: 'Carlos Ruiz',
            createdAt: getRandomTimestamp(23, 1),
        },
        {
            productId: 2,
            type: 'addition',
            quantity: 45,
            previousStock: 26,
            newStock: 71,
            reason: 'Bulk purchase',
            orderId: null,
            createdBy: 'Manager',
            createdAt: getRandomTimestamp(24, 0.5),
        },
        {
            productId: 8,
            type: 'reduction',
            quantity: 5,
            previousStock: 44,
            newStock: 39,
            reason: 'Staff meal',
            orderId: null,
            createdBy: 'Admin',
            createdAt: getRandomTimestamp(24.5, 0.5),
        },
        {
            productId: 12,
            type: 'addition',
            quantity: 18,
            previousStock: 5,
            newStock: 23,
            reason: 'Weekly delivery',
            orderId: null,
            createdBy: 'Manager',
            createdAt: getRandomTimestamp(25, 1),
        },

        // Days 26-28 - 4 movements
        {
            productId: 5,
            type: 'sale',
            quantity: 9,
            previousStock: 34,
            newStock: 25,
            reason: 'Sold to customer',
            orderId: null,
            createdBy: 'Maria Lopez',
            createdAt: getRandomTimestamp(26, 1),
        },
        {
            productId: 9,
            type: 'sale',
            quantity: 7,
            previousStock: 36,
            newStock: 29,
            reason: 'Walk-in customer',
            orderId: null,
            createdBy: 'Carlos Ruiz',
            createdAt: getRandomTimestamp(27, 0.5),
        },
        {
            productId: 3,
            type: 'reduction',
            quantity: 2,
            previousStock: 76,
            newStock: 74,
            reason: 'Damaged during prep',
            orderId: null,
            createdBy: 'Admin',
            createdAt: getRandomTimestamp(27.5, 0.5),
        },
        {
            productId: 6,
            type: 'adjustment',
            quantity: 12,
            previousStock: 44,
            newStock: 56,
            reason: 'Physical count adjustment',
            orderId: null,
            createdBy: 'System',
            createdAt: getRandomTimestamp(28, 1),
        },

        // Days 29-30 - 4 movements
        {
            productId: 10,
            type: 'addition',
            quantity: 28,
            previousStock: 13,
            newStock: 41,
            reason: 'Restock from supplier',
            orderId: null,
            createdBy: 'Manager',
            createdAt: getRandomTimestamp(29, 0.5),
        },
        {
            productId: 4,
            type: 'sale',
            quantity: 6,
            previousStock: 14,
            newStock: 8,
            reason: 'Phone order',
            orderId: null,
            createdBy: 'Maria Lopez',
            createdAt: getRandomTimestamp(29.5, 0.3),
        },
        {
            productId: 11,
            type: 'return',
            quantity: 3,
            previousStock: 22,
            newStock: 25,
            reason: 'Quality issue return',
            orderId: null,
            createdBy: 'Admin',
            createdAt: getRandomTimestamp(29.8, 0.2),
        },
        {
            productId: 1,
            type: 'sale',
            quantity: 11,
            previousStock: 78,
            newStock: 67,
            reason: 'Walk-in customer',
            orderId: null,
            createdBy: 'Carlos Ruiz',
            createdAt: getRandomTimestamp(30, 0.5),
        },
    ];

    await db.insert(inventoryMovements).values(sampleMovements);
    
    console.log('✅ Inventory movements seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});